vpn/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('svp/wireguard/', include('wireguard.urls')),
    path('svp/', include('accounts.urls')),
    path('svp/admin/', admin.site.urls),
]

wireguard/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'wireguard'
urlpatterns = [
    path('home/', views.HomeView.as_view(), name='home'),
    path('peer-new', views.PeerNewView.as_view(), name='peer-new'),
    path('peer/<int:pk>/detail', views.PeerDetailView.as_view(), name='peer-detail'),
    path('peers/', views.PeerListView.as_view(), name='peer-list'),
    path('peer/<int:pk>/delete', views.PeerDeleteView.as_view(), name='peer-delete'),

    path('server-new/', views.ServerNewView.as_view(), name='server-new'),
    path('servers/', views.ServerListView.as_view(), name='server-list'),
    path('server/<slug:interface>/', views.ServerSubsetView.as_view(), name='server-subset'),
    path('server/<int:pk>/delete', views.ServerDeleteView.as_view(), name='server-delete'),
]

wireguard/models.py
from django.utils.timezone import now

from django.db import models


class Server(models.Model):
    interface = models.CharField(max_length=50, unique=True)
    private_key = models.CharField(max_length=255, unique=True)
    public_key = models.CharField(max_length=255, unique=True)
    address = models.CharField(max_length=255, unique=True, default='10.0.0.1/24')
    endpoint = models.CharField(max_length=255)
    listen_port = models.BigIntegerField(unique=True, null=True, default=51820)
    post_up = models.TextField(max_length=255)
    post_down = models.TextField(max_length=255)
    save_config = models.BooleanField(default=True)
    created_at = models.DateTimeField(default=now)

    def __str__(self):
        return self.interface


class Peer(models.Model):
    server = models.ForeignKey(Server, related_name='peers', on_delete=models.SET_NULL, null=True)

    profile_name = models.CharField(max_length=255, null=True, blank=True)
    email = models.EmailField(null=True, blank=True)
    private_key = models.CharField(max_length=255, unique=True)
    public_key = models.CharField(max_length=255, unique=True)
    preshared_key = models.CharField(max_length=255, null=True, blank=True)
    address = models.CharField(max_length=255, unique=True)
    endpoint = models.CharField(max_length=255, null=True, blank=True)
    listen_port = models.BigIntegerField(null=True, default=51820)
    allowed_ips = models.CharField(max_length=255, default='0.0.0.0/0, ::/0')
    dns = models.CharField(max_length=255, default='1.1.1.1, 1.0.0.1')
    created_at = models.DateTimeField(default=now)

    def __str__(self):
        return self.profile_name

wireguard/forms/PeerNewForm.py
from django import forms
from wireguard.models import *


class PeerNewForm(forms.Form):
    server = forms.ModelChoiceField(label='Server', queryset=Server.objects.all(), empty_label=None, widget=forms.Select(attrs={'class': 'select', 'style': 'min-width:150px'}))
    peer = forms.CharField(label='Peer Name', widget=forms.TextInput(attrs={'class': 'input is-primary', 'autocomplete': 'off'}))
    email = forms.EmailField(widget=forms.TextInput(attrs={'class': 'input is-primary', 'autocomplete': 'off'}))
    dns = forms.CharField(label='DNS', widget=forms.TextInput(attrs={'class': 'input', 'autocomplete': 'off'}))
    address = forms.CharField(label='Address (eg. 10.0.0.2/24)', widget=forms.TextInput(attrs={'class': 'input', 'autocomplete': 'off'}))
    allowed_ips = forms.CharField(label='Allowed IPs (eg. 0.0.0.0/0, ::/0)', widget=forms.TextInput(attrs={'class': 'input', 'autocomplete': 'off'}))

wireguard/forms/ServerNewForm.py
from django import forms
from wireguard.models import *


class ServerNewForm(forms.Form):
    interface = forms.CharField(label='Interface', widget=forms.TextInput(attrs={'class': 'input is-primary', 'autocomplete': 'off'}))
    private_key = forms.CharField(label='Private Key', widget=forms.TextInput(attrs={'class': 'input is-primary', 'autocomplete': 'off'}))
    public_key = forms.CharField(label='Public Key', widget=forms.TextInput(attrs={'class': 'input is-primary', 'autocomplete': 'off'}))
    address = forms.CharField(label='Address (eg. 10.0.0.1/24)', widget=forms.TextInput(attrs={'class': 'input is-primary', 'autocomplete': 'off'}))
    endpoint = forms.CharField(label='EndPoint', widget=forms.TextInput(attrs={'class': 'input is-primary', 'autocomplete': 'off'}))
    listen_port = forms.IntegerField(label='Listen Port', widget=forms.NumberInput(attrs={'min': '49152', 'max': '65535', 'class': 'input', 'autocomplete': 'off'}))
    post_up = forms.CharField(label='Post Up', widget=forms.Textarea(attrs={'rows': 4, 'class': 'textarea', 'autocomplete': 'off'}))
    post_down = forms.CharField(label='Post Down', widget=forms.Textarea(attrs={'rows': 4, 'class': 'textarea', 'autocomplete': 'off'}))
    save_config = forms.CharField(label='Save Config', widget=forms.CheckboxInput(), required=False)

wireguard/views.py
import os
import tarfile
import random

from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

from django.urls import reverse_lazy
from django.conf import settings
from django.views import generic

from .models import Server, Peer

from .forms.PeerNewForm import PeerNewForm
from .forms.ServerNewForm import ServerNewForm
from django.views.generic.edit import FormView, DeleteView


@method_decorator(login_required, name='dispatch')
class HomeView(generic.ListView):
    model = Server
    template_name = 'layouts/home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['peers'] = Peer.objects.all().order_by('-created_at')[:5]
        context['servers'] = Server.objects.all().order_by('-created_at')[:5]
        context['peer_count'] = Peer.objects.all().count()
        context['server_count'] = Server.objects.all().count()

        return context


@method_decorator(login_required, name='dispatch')
class ServerNewView(FormView):
    template_name = 'layouts/server/server-new.html'
    form_class = ServerNewForm
    success_url = '/svp/wireguard/servers'

    def get_initial(self):
        initial = super().get_initial()

        os.system("mkdir -p {} && umask 077 {}"
                  .format(settings.WIREUGARD_TMP, settings.WIREUGARD_TMP))
        os.system("wg genkey | tee {}/server_private_key | wg pubkey | tee {}/server_public_key"
                  .format(settings.WIREUGARD_TMP, settings.WIREUGARD_TMP))

        private_key = os.popen(
            'cat {}/server_private_key'.format(settings.WIREUGARD_TMP)).read()
        public_key = os.popen(
            'cat {}/server_public_key'.format(settings.WIREUGARD_TMP)).read()

        initial['interface'] = "wg0"
        initial['post_up'] = "iptables -A FORWARD -i %i -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE"
        initial[
            'post_down'] = "iptables -D FORWARD -i %i -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE"
        initial['private_key'] = private_key.strip()
        initial['public_key'] = public_key.strip()
        initial['address'] = '10.0.0.1/24'
        initial['listen_port'] = random.randint(49152, 65535)

        return initial

    def form_valid(self, form):
        interface = form.cleaned_data['interface']
        private_key = form.cleaned_data['private_key']
        public_key = form.cleaned_data['public_key']
        address = form.cleaned_data['address']
        endpoint = form.cleaned_data['endpoint']
        listen_port = form.cleaned_data['listen_port']
        post_up = form.cleaned_data['post_up'].strip()
        post_down = form.cleaned_data['post_down'].strip()
        save_config = form.cleaned_data['save_config']

        server = Server.objects.create(
            interface=interface, private_key=private_key, public_key=public_key,
            address=address, endpoint=endpoint, listen_port=listen_port, post_up=post_up, post_down=post_down,
            save_config=save_config)

        server.save()

        os.system('echo {} >> {}server.{}.key'.format(
            private_key, settings.WIREGUARD_SERVER_KEYS, interface))
        os.system('echo {} >> {}server.{}.pub'.format(
            public_key, settings.WIREGUARD_SERVER_KEYS, interface))

        os.system('echo [Interface] "\n"Address = {} "\n"PrivateKey = {} "\n"ListenPort = {} "\n"PostUp = "{}" '
                  '"\n"PostDown = "{}" "\n"SaveConfig = {} >> {}{}.conf'.format(address, private_key, listen_port,
                                                                                str(post_up), str(
                post_down),
                                                                                save_config,
                                                                                settings.WIREGUARD_SERVER_CONF,
                                                                                interface))

        os.system('rm -rf {}private_key'.format(settings.WIREGUARD_SERVER_KEYS))
        os.system('rm -rf {}public_key'.format(settings.WIREGUARD_SERVER_KEYS))

        return super().form_valid(form)


@method_decorator(login_required, name='dispatch')
class ServerListView(generic.ListView):
    model = Server
    template_name = 'layouts/server/servers.html'
    context_object_name = 'servers'


@method_decorator(login_required, name='dispatch')
class ServerSubsetView(generic.ListView):
    model = Server
    template_name = 'layouts/server/server-subset.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['peers'] = Peer.objects.filter(
            server__interface=self.kwargs['interface'])
        context['server'] = Server.objects.get(
            interface=self.kwargs['interface'])
        return context


@method_decorator(login_required, name='dispatch')
class ServerDeleteView(generic.DeleteView):
    model = Server
    template_name = 'layouts/server/server-delete.html'
    success_url = reverse_lazy('wireguard:server-list')


@method_decorator(login_required, name='dispatch')
class PeerNewView(FormView):
    template_name = 'layouts/peer/peer-new.html'
    form_class = PeerNewForm
    success_url = 'home'

    def get_initial(self):
        initial = super().get_initial()
        initial['dns'] = '1.1.1.1, 1.0.0.1'
        initial['address'] = '10.0.0.2/24'
        initial['allowed_ips'] = '0.0.0.0/0, ::/0'

        return initial

    def form_valid(self, form):
        server = Server.objects.get(interface=form.cleaned_data['server'])

        peer = form.cleaned_data['peer']

        os.system('mkdir -p {}{}'.format(settings.WG_PROFILES, peer))

        peer_path = os.path.join(settings.WG_PROFILES, peer)

        os.system("wg genkey | tee {}-private | wg pubkey > {}-public"
                  .format(peer_path + "/" + peer, peer_path + "/" + peer))
        os.system("wg genpsk > {}-preshared".format(peer_path + "/" + peer))

        private_key = os.popen('cat {}-private'.format(peer_path + "/" + peer)).read()
        public_key = os.popen('cat {}-public'.format(peer_path + "/" + peer)).read()
        preshared_key = os.popen('cat {}-preshared'.format(peer_path + "/" + peer)).read()

        os.system('echo [Interface] "\n"Address = {} "\n"PrivateKey = {} "\n"DNS = {} "\n\n"[Peer] "\n"PublicKey = {} '
                  '"\n"PresharedKey = {} "\n"AllowedIPs = {} "\n"Endpoint = {}:{} >> {}.conf'.format(
            form.cleaned_data['address'],
            private_key.strip(),
            form.cleaned_data['dns'],
            server.public_key,
            preshared_key.strip(),
            form.cleaned_data['allowed_ips'].strip(),
            server.endpoint, server.listen_port,
            peer_path + "/" + peer))

        os.system("qrencode --foreground=111111 --background=896A67 -o {}-qrcode-dark.png < {}.conf".format(
            peer_path + "/" + peer, peer_path + "/" + peer))
        os.system("qrencode -o {}-qrcode-light.png < {}.conf".format(peer_path +
                                                                     "/" + peer, peer_path + "/" + peer))

        with tarfile.open(peer + ".tar.gz", "w:gz") as tar:
            tar.add(peer_path, arcname=os.path.basename(peer_path))

        os.system("mv {} {}".format(peer + ".tar.gz", settings.WIREGUARD_TARS))

        obj = Peer()

        obj.profile_name = form.cleaned_data['peer']
        obj.email = form.cleaned_data['email']
        obj.private_key = private_key
        obj.public_key = public_key
        obj.preshared_key = preshared_key
        obj.address = form.cleaned_data['address']
        obj.endpoint = server.endpoint
        obj.listen_port = server.listen_port
        obj.dns = form.cleaned_data['dns']
        obj.allowed_ips = form.cleaned_data['allowed_ips']
        obj.server = form.cleaned_data['server']

        obj.save()

        os.system('echo {} >> {}peer.{}.key'.format(
            private_key.strip(), settings.WIREGUARD_PEER_KEYS, peer))
        os.system('echo {} >> {}peer.{}.pub'.format(
            public_key.strip(), settings.WIREGUARD_PEER_KEYS, peer))
        os.system('echo {} >> {}peer.{}.pre'.format(
            preshared_key.strip(), settings.WIREGUARD_PEER_KEYS, peer))

        os.system('echo [Interface] "\n"Address = {} "\n"PrivateKey = {} "\n"DNS = {} "\n\n"[Peer] "\n"PublicKey = {} '
                  '"\n"PresharedKey = {} "\n"AllowedIPs = {} "\n"Endpoint = {}:{} >> {}{}.conf'.format(
            form.cleaned_data['address'],
            private_key.strip(),
            form.cleaned_data['dns'],
            server.public_key,
            preshared_key.strip(),
            form.cleaned_data['allowed_ips'].strip(),
            server.endpoint,
            server.listen_port,
            settings.WIREGUARD_PEER_CONF,
            peer))

        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['interfaces'] = Server.objects.all()
        return context


@method_decorator(login_required, name='dispatch')
class PeerDetailView(generic.DetailView):
    model = Peer
    template_name = 'layouts/peer/peer-detail.html'


@method_decorator(login_required, name='dispatch')
class PeerListView(generic.ListView):
    model = Peer
    template_name = 'layouts/peer/peers.html'

    def get_context_data(self, **kwargs):
        context = super(PeerListView, self).get_context_data(**kwargs)
        context['peers'] = Peer.objects.all()

        return context


@method_decorator(login_required, name='dispatch')
class PeerDeleteView(generic.DeleteView):
    model = Peer
    template_name = 'layouts/peer/peer-delete.html'
    success_url = reverse_lazy('wireguard:home')

wireguard/templates/layouts/home.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Generate Server Keys {% endblock title %}

{% block body %}
    {% include 'includes/navbar.html' %}
    <div class="section wireguard-home">
        <div class="container">
            <div class="columns">
                <div class="column is-12">
                    <div class="columns">
                        <div class="column is-10 is-12-touch">
                            <div class="wg-logo mb-5">
                                <img src="{% static 'images/wireguard-logo.png' %}" width="400" height="50">
                            </div>
                            <h3 class="is-size-4">Welcome, Friend!</h3>
                            <br>
                            <p>This tool is to assist with creating config files for a WireGuard clients.<br />
                                Simply enter the parameters for your particular setup and click Generate Config to get started.</p>
                            <br><br>

                            {% include 'includes/status.html' %}

                            <div class="columns">
                                <div class="column is-6 latest-clients">
                                    <h4 class="mb-4"><svg role="img" xmlns="http://www.w3.org/2000/svg" width="28px" height="28px" viewBox="0 0 24 24" aria-labelledby="peopleIconTitle" stroke="#DF9B6D" stroke-width="1" stroke-linecap="square" stroke-linejoin="miter" fill="none" color="#DF9B6D"> <title id="peopleIconTitle">People</title> <path d="M1 18C1 15.75 4 15.75 5.5 14.25 6.25 13.5 4 13.5 4 9.75 4 7.25025 4.99975 6 7 6 9.00025 6 10 7.25025 10 9.75 10 13.5 7.75 13.5 8.5 14.25 10 15.75 13 15.75 13 18M12.7918114 15.7266684C13.2840551 15.548266 13.6874862 15.3832994 14.0021045 15.2317685 14.552776 14.9665463 15.0840574 14.6659426 15.5 14.25 16.25 13.5 14 13.5 14 9.75 14 7.25025 14.99975 6 17 6 19.00025 6 20 7.25025 20 9.75 20 13.5 17.75 13.5 18.5 14.25 20 15.75 23 15.75 23 18"/> <path stroke-linecap="round" d="M12,16 C12.3662741,15.8763472 12.6302112,15.7852366 12.7918114,15.7266684"/> </svg> Latest Clients</h4>
                                    {% if peers %}
                                        {% for peer in peers %}
                                            <div class="box peer">
                                                <span class="tag-server">{{ peer.server }}</span>
                                                <a href="{% url 'wireguard:peer-detail' peer.id %}" class="media">
                                                    <div class="media-left">
                                                        <figure class="image is-64x64">
                                                            <img src="{% static 'profiles' %}/{{ peer }}/{{ peer.profile_name }}-qrcode-light.png" alt="Image">
                                                        </figure>
                                                    </div>
                                                    <div class="media-content">
                                                        <div class="content">
                                                            <p>
                                                                <strong>{{ peer.profile_name }}</strong> <time>{{ peer.created_at }}</time>
                                                                <br>
                                                                <span>{{ peer.allowed_ips }}</span>
                                                                <br>
                                                                <span>{{ peer.endpoint }}:{{ peer.listen_port }}</span>
                                                            </p>
                                                        </div>
                                                    </div>
                                                </a>
                                            </div>
                                        {% endfor %}
                                    {% else %}
                                        <div class="message is-warning warning-peer">
                                            <div class="message-header">
                                                <p>Warning</p>
                                            </div>
                                            <div class="message-body">
                                                <span class="is-size-5">There are no peer keys has generated yet.</span>
                                                <br><br>
                                                <a href="{% url 'wireguard:peer-new' %}" class="button btn-custom-dark">Add Peer</a>
                                            </div>
                                        </div>
                                    {% endif %}
                                </div>

                                <div class="column is-6 latest-servers">
                                    <h4 class="mb-4"><svg role="img" xmlns="http://www.w3.org/2000/svg" width="28px" height="28px" viewBox="0 0 24 24" aria-labelledby="listIconTitle" stroke="#DF9B6D" stroke-width="1" stroke-linecap="square" stroke-linejoin="miter" fill="none" color="#DF9B6D"> <title id="listIconTitle"/> <path d="M10 7L18 7M10 12L18 12M10 17L18 17"/> <line x1="7" y1="7" x2="7" y2="7"/> <line x1="7" y1="12" x2="7" y2="12"/> <line x1="7" y1="17" x2="7" y2="17"/> </svg> Latest Servers</h4>
                                    {% if servers %}
                                        {% for server in servers %}
                                            <div class="box server">
                                                <a href="{% url 'wireguard:server-delete' server.pk %}"><span class="tag-remove"><svg role="img" xmlns="http://www.w3.org/2000/svg" width="18px" height="18px" viewBox="0 0 24 24" aria-labelledby="closeIconTitle" stroke="#DF9B6D" stroke-width="1" stroke-linecap="square" stroke-linejoin="miter" fill="none" color="#DF9B6D"> <title id="closeIconTitle">Close</title> <path d="M6.34314575 6.34314575L17.6568542 17.6568542M6.34314575 17.6568542L17.6568542 6.34314575"/></svg></span></a>
                                                <a href="{% url 'wireguard:server-subset' server.interface %}" class="media">
                                                    <div class="media-content">
                                                        <div class="content">
                                                            <p>
                                                                <strong>{{ server.interface }}</strong> <time>{{ server.created_at }}</time>
                                                                <br>
                                                                <span>{{ server.address }}</span>
                                                                <br>
                                                                <span>{{ server.endpoint }}:{{ server.listen_port }}</span>
                                                            </p>
                                                        </div>
                                                    </div>
                                                </a>
                                            </div>
                                        {% endfor %}
                                    {% else %}
                                        <div class="message is-warning warning-server">
                                            <div class="message-header">
                                                <p>Warning</p>
                                            </div>
                                            <div class="message-body">
                                                <span class="is-size-5">There are no server keys has generated yet.</span>
                                                <br><br>
                                                <a href="{% url 'wireguard:server-new' %}" class="button btn-custom-dark">Add Server</a>
                                            </div>
                                        </div>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock body %}

{% block footer %}
    {% include 'includes/footer.html' %}
{% endblock footer %}